# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d294e7f0f1ca722c108aa6ee9e27e75dd5e2c234bcdcc1e400944c6750a5eb95ea7cfcc68654e991a40d5833543f32c0e4c27a2bde43c5179ac5108b2792c73

test:
  secret_key_base: 175162281475964684cef45a1ee453ee130e8bba7f132fbfc5f9ae391c277f58edf21f22a6ac02c53f1643a48285891a4b9fa7f464ea87cc40fbbddd96f25a10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
